name: Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/build-push-action@v4
        with:
          push: true
